version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adminpw
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - /etc/gogs:/data
    depends_on:
      - mysql
volumes:
  mysql: {}

